### ISSUE TITLE
Example Page Problem

### ISSUE THREAD

**Issue by impulsecorp** [FragileTheory/FractalAI#88]
I tried your program on my server and it worked fine, but I am confused by the results.  When I try the example you created at https://github.com/FragileTheory/FractalAI/blob/master/swarm_wave_example.ipynb, while it is training it shows good results like:
---------------------------------
Environment: MsPacman-ram-v0 | Walkers: 100 | Deaths: 0 | data_size 79
Total samples: 4301 Progress: 86.02%
Reward: mean 269.60 | Dispersion: 60.00 | max 290.00 | min 230.00 | std 15.29
Episode length: mean 47.24 | Dispersion 19.00 | max 56.00 | min 37.00 | std 5.39
Dt: mean 3.65 | Dispersion: 5.00 | max 8.00 | min 3.00 | std 1.05
Status: Sample limit reached.
----------------------------------
but then at the end it does not show me the final results, it just shows:
----------------------------------
Environment: MsPacman-ram-v0 | Walkers: 100 | Deaths: 100 | data_size 100
Total samples: 349 Progress: 6.98%
Reward: mean 0.00 | Dispersion: 0.00 | max 0.00 | min 0.00 | std 0.00
Episode length: mean 3.49 | Dispersion 6.00 | max 9.00 | min 3.00 | std 1.07
Dt: mean 3.49 | Dispersion: 6.00 | max 9.00 | min 3.00 | std 1.07
Status: All the walkers died.
----------------------------------
which is not like your demo page at  
https://github.com/FragileTheory/FractalAI/blob/master/swarm_wave_example.ipynb
where it shows at the end it shows the final results:
---------------------------------
Environment: MsPacman-ram-v0 | Walkers: 250 | Deaths: 0 | data_size 408
Total samples: 393884 Progress: 100.11%
Reward: mean 9577.57 | Dispersion: 481.00 | max 10011.00 | min 9530.00 | std 43.67
Episode length: mean 1702.92 | Dispersion 50.00 | max 1721.00 | min 1671.00 | std 12.78
Dt: mean 4.15 | Dispersion: 5.00 | max 8.00 | min 3.00 | std 1.35
Status: Score limit reached.
Efficiency 0.40%
Generated 1580 Examples | 249.29 samples per example.
CPU times: user 7.66 s, sys: 202 ms, total: 7.87 s
Wall time: 42.4 s
----------------------------------

**Comment by sergio-hcsoft** [comment]
There is no "training" here, you just run the code, wait, and get a nice score with its video.

When you run the code, it will stop when the sample/score limit are reached (like in your 1st example) or the game killed you (second case, "Status: All the walkers died"). After that, if you selected to save the examples (I see you opted for saving them) then, running the next jupyter cells should show you the video of the game played.
