### ISSUE TITLE
Scaling question

### ISSUE THREAD

**Issue by impulsecorp** [FragileTheory/FractalAI#89]
You wrote:  "Please, do not try to use this code in a real world application, because it wont scale well. "
and 
"This single core implementation can generate on MsPacman about 30k high quality samples per minute. So properly scaled you should be able to feed NNs like a boss."

Is there reason it would be difficult to change the code to run multicore?

**Comment by sergio-hcsoft** [comment]
The code already runs in multicore but this comment is not updated. In both example notebooks (FMC and Swarm Wave) you will find a parm "workers=8", this is how many cores to use.

Before multi-core and before Swarm Wave, FMC was able to manage about 500-1000 walkers at most, not Wave version with many cores can easily scale to 20k, so now it scales quite well, but still not as intended (we want to be able to reach millions in a cheap way).
